ISOFLAT = "ISOFLAT"

ISOFLAT_BR_PREFIX = 'ibr-'
ISOFLAT_IF_PREFIX = 'iif-'
PHYSIBR_IF_PREFIX = 'pif-'
ISOFLAT_IF_LENGTH = 14
DEFAULT_BRIDGE_MAPPINGS = []

TOPIC_ISOFLAT_PLUGIN = 'neutron-isoflat-plugin'
TOPIC_ISOFLAT_AGENT = 'neutron-isoflat-agent'

DESCRIPTION_FIELD_SIZE = 255
